"""
FlyRank Backend Track — Week 2 Assignment: Containerize your stack (BE-04)

Same Task API as Week 1 — routes and service logic are UNCHANGED. The only
difference is storage: this now runs against a real Postgres database
inside Docker instead of an in-memory dict. See app/repository.py for
where that swap actually happens.

Run locally (after `docker compose up` has Postgres running):
    uvicorn app.main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from fastapi.requests import Request

from app.database import init_db
from app.exceptions import TaskNotFoundError
from app.models import TaskCreate, TaskUpdate, TaskResponse
from app.repository import task_repository


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Create the `tasks` table if it doesn't exist yet. Only new addition vs. Week 1."""
    init_db()
    yield


app = FastAPI(
    title="FlyRank Task API",
    description="Week 2 Backend AI Engineering assignment — Task API backed by Postgres.",
    version="2.0.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------
# Centralizing this here means every endpoint gets consistent error JSON
# without repeating try/except blocks in each route. This is the "error
# handling" half of the assignment brief.

@app.exception_handler(TaskNotFoundError)
async def task_not_found_handler(request: Request, exc: TaskNotFoundError):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content={"error": "task_not_found", "message": str(exc)},
    )


@app.exception_handler(RequestValidationError)
async def validation_error_handler(request: Request, exc: RequestValidationError):
    title_errors = ("missing", "value_error", "string_too_short")
    has_title_error = any(
        err.get("loc") == ("body", "title") and err.get("type") in title_errors
        for err in exc.errors()
    )
    if has_title_error:
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={
                "error": "validation_error",
                "message": "Title is required and must not be empty.",
            },
        )
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": exc.errors()},
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", tags=["meta"])
def root():
    return {"name": "Task API", "version": "2.0", "endpoints": ["/tasks"]}


@app.get("/health", tags=["meta"])
def health_check():
    """Simple liveness check — useful once this gets containerized/deployed."""
    return {"status": "ok"}


@app.post(
    "/tasks",
    response_model=TaskResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["tasks"],
)
def create_task(payload: TaskCreate):
    """Create a new task. Returns 201 with the created resource."""
    task = task_repository.create(payload)
    return task


@app.get("/tasks", response_model=list[TaskResponse], tags=["tasks"])
def list_tasks():
    """List all tasks. Returns 200 with an array (empty array if none exist)."""
    return task_repository.list_all()


@app.get("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def get_task(task_id: int):
    """Get a single task by id. Returns 404 if it doesn't exist."""
    return task_repository.get(task_id)


@app.put("/tasks/{task_id}", response_model=TaskResponse, tags=["tasks"])
def update_task(task_id: int, payload: TaskUpdate):
    """Partially update a task. Returns 404 if it doesn't exist."""
    return task_repository.update(task_id, payload)


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["tasks"])
def delete_task(task_id: int):
    """Delete a task. Returns 204 (no body) on success, 404 if missing."""
    task_repository.delete(task_id)
    return None
